name: DuckPrisons
version: '${project.version}'
main: colton.duckprisons.DuckPrisons
api-version: 1.19
authors: [ TheCodingDuck (colton-boi) ]
description: Prisons plugin created by TheCodingDuck for ValidGens
commands:
  test:

  getPickaxe:
